---
name: Reusable Test
on:
  pull_request:
    inputs: {}

jobs:
  trigger:
    uses: ./.github/workflows/ReusableWorkflow.yml

  duplicate:
    runs-on: ubuntu-latest
    steps:
      - run: jq <"$GITHUB_EVENT_PATH"
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: julia-actions/setup-julia@v2
        with:
          version: "1"
      - name: Save cache
        uses: ./

  compare:
    needs: duplicate
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::group::Raw A"
          jq <<<"$a"
          echo "::endgroup::"

          echo "::group::Raw B"
          jq <<<"$b"
          echo "::endgroup::"
          
          echo "::group::Diff"
          diff <(echo "$a") <(echo "$b")
          echo "::endgroup::"
        env:
          a: ${{ toJSON(github) }}
          b: ${{ needs.trigger.outputs.github-json }}
